language: php
dist: trusty
sudo: required

addons:
  sonarcloud:
    token:
      secure: "461c1bbbb607c98ccc4a68ec414f045eb949e1e5"
jdk:
  - oraclejdk8
script:
  - sonar-scanner
cache:
  directories:
    - '$HOME/.sonar/cache'